
export type PageId = 'INICIO' | 'NOSOTROS' | 'EVENTOS' | 'TRAINING' | 'FAQ' | 'CONTACTO' | 'MEMBRESÍA';

export const NAVIGATION_CONFIG: PageId[] = [
  'INICIO',
  'NOSOTROS',
  'EVENTOS',
  'TRAINING',
  'FAQ',
  'CONTACTO',
  'MEMBRESÍA'
];

export const SUB_MENU: Record<PageId, string[]> = {
  'INICIO': ['DASHBOARD', 'WEEKLY_NEWS', 'CORE_STATUS'],
  'NOSOTROS': ['MISIÓN', 'DIRECTIVA', 'HISTORIA'],
  'EVENTOS': ['CALENDARIO', 'TALLERES', 'CONTESTS'],
  'TRAINING': ['CODEFORCES', 'VJUDGE', 'RECURSOS_CPP'],
  'FAQ': ['REQUISITOS', 'COSTOS', 'BENEFICIOS'],
  'CONTACTO': ['DISCORD', 'INSTAGRAM', 'UBICACIÓN'],
  'MEMBRESÍA': ['REGISTRO_FORM', 'ESTADO_SOLICITUD']
};
